FROM debian:jessie

ENV DEBIAN_FRONTEND noninteractive
ENV DISPLAY :1

RUN apt-get update && apt-get -y install xserver-xorg-video-dummy x11-apps x11vnc

VOLUME /tmp/.X11-unix

COPY xorg.conf /etc/X11/xorg.conf

COPY start-xdummy.sh start.sh
CMD ["bash", "start.sh"]
